# Site settings
baseurl: "" 

# Color settings (Hex value without #)
color_alpha: 0a0a0a
color_beta: eeeeee

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Instagram API
instagram_key: 2237615866.1677ed0.2184cbe7894b41b2bc8d3218b27b6ded
instagram_caption: true

# SEO settings
title: Corbin Scott
description: Corbin Scott
url: "slykuiper.com"
email: corbin@slykuiper.com
twitter_username: Slykuiper
default_img: https://slykuiper.com/assets/images/logo.png

# Profile settings
name: Corbin Scott
social:
  twitter-square: http://twitter.com/Slykuiper
  dribbble-square: http://dribbble.com/slykuiper
  instagram: http://www.instagram.com/slykuiper
  youtube-square: https://www.youtube.com/slykuiper
  twitch: https://twitch.tv/slykuiper
  vimeo-square: https://vimeo.com/slykuiper

# Build settings
exclude: ["node_modules", "gulpfile.js", "assets/js/app.js", "README.md", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-sitemap, octopress-autoprefixer]